### ISSUE TITLE
This implementation is different from the description in the artical？

### ISSUE THREAD

**Issue by qianfangjj** [ayanb280/lwd_muesli#1]
I have read the code and found that there are some differences between the code and the article Muesli: Combining Improvements in Policy Optimization. For example, reward model are not found in this implementation

**Comment by ayanb280** [comment]
Hey @qianfangjj, yes, this model is not the same as Muesli. Here we are attempting to solve graph combinatorial optimization problems and are trying to see whether we can take any inspiration from Muesli.
